services:
    db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: 'submission_ws'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"

    slurmmaster:
        entrypoint: /compose_entrypoint.sh
        image: submission-ws
        hostname: slurmmaster
        user: root
        volumes:
            - shared-vol:/home/admin
        ports:
            - 6817:6817
            - 4821:4821
        links:
            - db
        environment:
            - DRMAATIC_CONFIG_PATH=/config.json
            - DJANGO_SUPERUSER_PASSWORD=admin
        
    slurmnode1:
        image: rancavil/slurm-node:19.05.5-1
        hostname: slurmnode1
        user: admin
        volumes:
            - shared-vol:/home/admin
        environment:
            - SLURM_NODENAME=slurmnode1
        links:
            - slurmmaster
            
volumes:
    shared-vol: