#!/bin/bash

: ${port:="8080"}
while true; do
  case "$1" in
    --port)
      port="$2"
      shift 2;;
    --)
    shift
      break;;
     *)
      break;
          ;;
  esac
done

SCRIPTS_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../submission_ws && pwd )"

echo $SCRIPTS_DIRECTORY
echo $APP_DIRECTORY

echo $( pwd )

(cd $APP_DIRECTORY && gunicorn server.wsgi --bind "0.0.0.0:$port")
# cd ../submission_ws && ./manage.py runserver "$port"