#!/bin/bash

: ${port:="4821"}
while true; do
  case "$1" in
    --port)
      port="$2"
      shift 2;;
    --)
    shift
      break;;
     *)
      break;
          ;;
  esac
done

# gunicorn server.wsgi --bind "0.0.0.0:$port"
submission-ws-manage runserver "0.0.0.0:$port"