#!/bin/bash

: ${port:="8080"}
while true; do
  case "$1" in
    --port)
      port="$2"
      shift 2;;
    --)
    shift
      break;;
     *)
      break;
          ;;
  esac
done

# SCRIPTS_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# PROJECT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../ && pwd )"

# echo $SCRIPTS_DIRECTORY
# echo $PROJECT_DIRECTORY

# echo $( pwd )

# (cd $PROJECT_DIRECTORY && 
gunicorn server.wsgi --bind "0.0.0.0:$port"
# cd ../submission_ws && ./manage.py runserver "$port"